// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3ZSBEn4G9WVmOYAiXYpzokXjVvyw89c',
    appId: '1:366979881087:web:f3e695d2d08f9c054e474a',
    messagingSenderId: '366979881087',
    projectId: 'travel-friends-e4959',
    authDomain: 'travel-friends-e4959.firebaseapp.com',
    storageBucket: 'travel-friends-e4959.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3jQo-OIgUiiFPgxKhp4j7uj0wOW1QdRI',
    appId: '1:366979881087:android:db659078080616da4e474a',
    messagingSenderId: '366979881087',
    projectId: 'travel-friends-e4959',
    storageBucket: 'travel-friends-e4959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamW_DNLBXwyaIE1SYtlYSrOlOO6orO_k',
    appId: '1:366979881087:ios:42397b05d1aadafe4e474a',
    messagingSenderId: '366979881087',
    projectId: 'travel-friends-e4959',
    storageBucket: 'travel-friends-e4959.appspot.com',
    iosBundleId: 'com.example.travelFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamW_DNLBXwyaIE1SYtlYSrOlOO6orO_k',
    appId: '1:366979881087:ios:31acbd3c248410e04e474a',
    messagingSenderId: '366979881087',
    projectId: 'travel-friends-e4959',
    storageBucket: 'travel-friends-e4959.appspot.com',
    iosBundleId: 'com.example.travelFriends.RunnerTests',
  );
}
